# Generated by Django 5.0.14 on 2026-09-23 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_ne', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(help_text='Short label, e.g. "Hotel", "Bakery", "Restaurant".', max_length=100)),
                ('sector_ne', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
                ('show_on_home', models.BooleanField(default=True, help_text='Include in the homepage "Selected projects" grid (first 4).')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('home_hero', 'Home - hero'), ('home_approach', 'Home - "Our approach"'), ('about_hero', 'About - hero'), ('about_partner', 'About - "A complete partner"'), ('about_team', 'About - team photo'), ('solutions_hero', 'Solutions - hero'), ('products_hero', 'Products - hero'), ('projects_hero', 'Projects - hero'), ('services_hero', 'Services - hero'), ('contact_hero', 'Contact - hero'), ('auth_panel', 'Login / register side panel'), ('category_burner', 'Category tile - Burner'), ('category_table', 'Category tile - Table'), ('category_rack', 'Category tile - Rack'), ('category_sink', 'Category tile - Sink'), ('category_showcase', 'Category tile - Showcase'), ('category_chiller', 'Category tile - Chiller'), ('category_fryer', 'Category tile - Fryer'), ('category_shelves', 'Category tile - Shelves'), ('category_chimney', 'Category tile - Chimney'), ('category_others', 'Category tile - Others')], max_length=40, unique=True)),
                ('image', models.ImageField(upload_to='site/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote', models.TextField(max_length=600)),
                ('quote_ne', models.TextField(blank=True, max_length=600)),
                ('source', models.CharField(help_text='Attribution, e.g. "Hotel client · Kathmandu".', max_length=200)),
                ('source_ne', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
