# Generated by Django 5.0.14 on 2026-08-25 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Burner', 'Burner'), ('Table', 'Table'), ('Rack', 'Rack'), ('Sink', 'Sink'), ('Showcase', 'Showcase'), ('Chiller', 'Chiller'), ('Fryer', 'Fryer'), ('Shelves', 'Shelves'), ('Chimney', 'Chimney'), ('Others', 'Others')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
