# Generated by Django 5.0.14 on 2026-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='order',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank to never expire.', null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('left', 'Left rail'), ('right', 'Right rail')], default='left', max_length=5),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank to start showing immediately.', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(help_text='Short promotional message shown on the ad card.', max_length=200),
        ),
    ]
