# Generated by Django 5.0.14 on 2026-08-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='promotions/'),
        ),
    ]
