# Generated by Django 5.0.14 on 2026-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('home_top', 'Homepage - below the hero'), ('home_bottom', 'Homepage - above the contact section'), ('products', 'Products page - above the catalogue'), ('popup', 'Popup - once per visit')], default='home_top', max_length=20),
        ),
    ]
